# $Id: ionC12.mac 101250 2016-11-10 08:54:02Z gcosmo $
#
# Macro file for "TestEm7.cc"
# (can be run in batch, without graphic)
#
/control/verbose 2
/run/verbose 2
/tracking/verbose 0
#
/testem/det/setMat SF6
/testem/det/setSizeX  20 cm
/testem/det/setSizeYZ 20 cm
#
/testem/det/tallyNumber 4
/testem/det/tallyDefinition 0 2. 2. 2. mm
/testem/det/tallyDefinition 1 2. 2. 2. mm
/testem/det/tallyDefinition 2 2. 2. 2. mm
/testem/det/tallyDefinition 3 2. 2. 2. mm
/testem/det/tallyPosition 0 -9.9 0. 0. cm
/testem/det/tallyPosition 1 -5.  0. 0. cm
/testem/det/tallyPosition 2  0.  0. 0. cm
/testem/det/tallyPosition 3  5.  0. 0. cm
#
# /testem/phys/addPhysics  emstandard_opt0
# /testem/phys/addPhysics  emstandard_opt1
# /testem/phys/addPhysics  emstandard_opt2
# /testem/phys/addPhysics  emstandard_opt3
/testem/phys/addPhysics  emstandard_opt4
# /testem/phys/addPhysics  ionGasModels
# /testem/phys/addPhysics  standardNR
# /testem/phys/addPhysics  emlivermore
# /testem/phys/addPhysics  empenelope
# /testem/phys/addPhysics  emlowenergy
# /testem/phys/addPhysics  emstandardSS
# /testem/phys/addPhysics  emstandardWVI
# /testem/phys/addPhysics  emstandardGS
# /testem/phys/addPhysics  elastic
# /testem/phys/addPhysics  DElastic
# /testem/phys/addPhysics  HElastic
# /testem/phys/addPhysics  binary
# /testem/phys/addPhysics  binary_ion
#
/run/initialize
#
/gun/particle ion
/gun/ion 9 18 9
/gun/energy 100 keV
#
# step limit
/run/setCut 0.01 um
#
/process/list
#
/run/printProgress 100
#
/run/beamOn 1000
#
