# Macro file for "TestEm7.cc"
# (can be run in batch, without graphic)
#
/control/verbose 2
/run/verbose 2
/tracking/verbose 0
#
#/testem/det/setSF6pressure 100 torr
/testem/det/setMixturePressure 50.e-3 bar
#
/testem/det/setSizeX  20 cm
/testem/det/setSizeYZ 20 cm
#
/testem/det/tallyNumber 0
#
# /testem/phys/addPhysics  FTFP_BERT_EMY
#/testem/phys/addPhysics  myem4had
/testem/phys/addPhysics  myem3had
# /testem/phys/addPhysics  FTFP_BERT_EMZ
# /testem/phys/addPhysics  FTFP_BERT_LIV
# /testem/phys/addPhysics  FTFP_BERT_PEN  
#
/run/initialize
#
/gun/particle ion
/gun/ion 6 12 1
#
# step limit
/run/setCut 0.1 um
#
/process/list
#
/analysis/setFileName F18_SF6_100keV
/analysis/h1/set 2 100 0 2 mm
/analysis/h1/set 3 100 0 2 mm
#
/run/printProgress 10000
#
/gun/energy 100 keV
/run/beamOn 1

