/testem/det/setMixturePressure 50.e-3 bar
/testem/det/setSizeX  20 cm
/testem/det/setSizeYZ 20 cm
/testem/det/tallyNumber 0
#/testem/phys/addPhysics  FTFP_BERT_EMY
#/testem/phys/addPhysics  myemhad
#/testem/phys/addPhysics ionGasModels
/testem/phys/addPhysics  FTFP_BERT_EMY

/tracking/verbose 0

/run/initialize

# step limit
/run/setCut 10 um
/testem/stepMax 100 um

/gun/particle ion
/gun/ion 6 12 1

/gun/energy 10 keV
/run/beamOn 1